name: run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2

      - name: Pull docker images
        run: make pull

      - name: Set up docker layers cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build docker images
        run: make build

      - name: Set up composer cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
            **/composer.lock
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make dependencies

      - name: Start the docker containers
        run: make up

      - name: Execute the tests
        run: make tests
